
export interface transmissionsModel {
  id?: 1,
  courier_cost?: number,
  commission?: number,
  random_code?: string,
  is_arrived?: boolean,
  is_received?: boolean,
  is_reached?: boolean,
  is_delivered?: boolean,
  is_done?: boolean,
  is_canceled?: boolean,
  date_accepted?: string,
  date_arrived?: string,
  date_received?: string,
  date_reached?: string,
  date_delivered?: string,
  date_done?: string,
  date_canceled?: string,
  is_paid?: boolean,
  is_paid_sms?: boolean,
  score?: number,
  is_scored?: boolean,
  created_for?: string,
  payment_type?: string,
  is_returning?: boolean,
  transfer_time?: string,
  transaction_id?: null,
  courier_id?: 1
}